// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJVHIH-o1fwbxY1ntJQ4vQUbIWNk7g4lc',
    appId: '1:613300918152:web:b6376caea9556094dd4c3d',
    messagingSenderId: '613300918152',
    projectId: 'tirrr-4df18',
    authDomain: 'tirrr-4df18.firebaseapp.com',
    storageBucket: 'tirrr-4df18.firebasestorage.app',
    measurementId: 'G-X16HL0HJJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFc69EurmjSBkn2jZRBDcXH7C4Si8otpI',
    appId: '1:613300918152:android:9f505174f11d583add4c3d',
    messagingSenderId: '613300918152',
    projectId: 'tirrr-4df18',
    storageBucket: 'tirrr-4df18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUgVcMQ-_xoF9_HNDSD0qCzNCkVBb01d8',
    appId: '1:613300918152:ios:10c841b4cbd3fb15dd4c3d',
    messagingSenderId: '613300918152',
    projectId: 'tirrr-4df18',
    storageBucket: 'tirrr-4df18.firebasestorage.app',
    iosBundleId: 'com.example.tirrrApp',
  );
}
